version: 1.0.{build}
clone_folder: '%solution_dir%'
init:
- ps: >-
    iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'));


    npm install -g bower;
environment:
  solution_dir: c:\src\repos\IIS.Administration
  publish_out_dir: c:\publish_out\IIS.Administration
services: iis
before_build:
- ps: dotnet restore
build:
  verbosity: minimal
after_build:
- ps: >-
    & "$env:solution_dir\scripts\publish\publish.ps1" -OutputPath $env:publish_out_dir -SkipRestore -SkipPrompt;


    Get-WindowsOptionalFeature -Online | where {$_.FeatureName -match "IIS-" -and $_.State -eq [Microsoft.Dism.Commands.FeatureState]::Disabled} | % {Enable-WindowsOptionalFeature -Online -FeatureName $_.FeatureName};


    & "$env:publish_out_dir\setup\setup.ps1" Install -Verbose -Port 44326
test_script:
- ps: dotnet test "$env:solution_dir\test\Microsoft.IIS.Administration.Tests"